export const Page = [
    {
        id: "1",
        image: "/images/cp1.webp",
        name: "The Raahi Inn",
        subname: "Udaipur",
        map: "show on map",
        town: "4.2 km from downtown",
        room: "Standard Double Room",
        bed: "2 twin beds",
        service: "Free cancellation",
        pay: "No prepayment needed - pay at the property",
        roomleft: "Only 2 rooms left at this price on our site",
        btn: "New to Booking.com",
        rate: "",
        review : "",
        no: "",
        loc: "",
        people: "2 nights, 2 adults",
        rupee: "₹ 3,600",
        tax: "+₹ 432 taxes and fees",
        see: " See availability >"
    },
    {
        id: "2",
        image: "/images/cp2.webp",
        name: "Narayana Hotel and BAR near Railway Station Udaipur",
        subname: "Udaipur",
        map: "show on map",
        town: "0.8 km from downtown",
        room: "Budget Double or Twin Room",
        bed: "1 full bed",
        service: "Free cancellation",
        pay: "No prepayment needed - pay at the property",
        roomleft: "Only 3 rooms left at this price on our site",
        btn: "New to Booking.com",
        rate: "Exceptional",
        review : "10 reviews",
        no: "10",
        loc: "Location 10",
        people: "2 nights, 2 adults",
        rupee: "₹ 2,977",
        tax: "+₹ 357 taxes and fees",
        see: " See availability >"
    },
    {
        id: "3",
        image: "/images/cp3.webp",
        name: "Barefoot Boutique Hotel Udaipur",
        subname: "Lal Ghat, Udaipur(Lal Ghat)",
        map: "show on map",
        town: "1.5 km from downtown",
        room: "Executive Queen Room with Two Queen Beds",
        bed: "2 full beds",
        service: "Free cancellation",
        pay: "No prepayment needed - pay at the property",
        roomleft: "Only 1 rooms left at this price on our site",
        btn: "",
        rate: "Excellent",
        review : "203 reviews",
        no: "8.8",
        loc: "Location 9.5",
        people: "2 nights, 2 adults",
        rupee: "₹ 3,060",
        tax: "+₹ 367 taxes and fees",
        see: " See availability >"
    },
    {
        id: "4",
        image: "/images/cp4.webp",
        name: "Lassi Guest House",
        subname: "Udaipur",
        map: "show on map",
        town: "1.9 km from downtown",
        room: "Budget Double Room",
        bed: "1 full bed",
        service: "",
        pay: "",
        roomleft: "Only 1 rooms left at this price on our site",
        btn: "",
        rate: "Wonderful",
        review : "384 reviews",
        no: "9.2",
        loc: "Location 9.6",
        people: "2 nights, 2 adults",
        rupee: "₹ 2,700",
        tax: "+₹ 324 taxes and fees",
        see: " See availability >"
    },
    {
        id: "5",
        image: "/images/cp5.webp",
        name: "Amet Haveli - A Heritage Hotel Udaipur",
        subname: "Udaipur",
        map: "show on map",
        town: "1.8 km from downtown",
        room: "Standard Double Room",
        bed: "1 King bed",
        service: "Breakfast included",
        pay: "",
        roomleft: "Only 2 rooms left at this price on our site",
        btn: "",
        rate: "Excellent",
        review : "379 reviews",
        no: "8.6",
        loc: "Location 9.6",
        people: "2 nights, 2 adults",
        rupee: "₹ 8,000",
        tax: "+₹ 960 taxes and fees",
        see: " See availability >"
    },
    {
        id: "6",
        image: "/images/cp6.webp",
        name: "Asra Lake Heritage Hotel with rooftop and swimming pool",
        subname: "Udaipur",
        map: "show on map",
        town: "2.1 km from downtown",
        room: "Double Room",
        bed: "1 full bed",
        service: "Free cancellation",
        pay: "No prepayment needed - pay at the property",
        roomleft: "",
        btn: "New to Booking.com",
        rate: "Exceptional",
        review : "12 reviews",
        no: "9.8",
        loc: "Location 9.8",
        people: "2 nights, 2 adults",
        rupee: "₹ 2,430",
        tax: "+₹ 292 taxes and fees",
        see: " See availability >"
    },
    {
        id: "7",
        image: "/images/cp7.webp",
        name: "Soham Haveli Udaipur",
        subname: "Udaipur",
        map: "show on map",
        town: "1.7 km from downtown",
        room: "Standard Double Room",
        bed: "1 king bed",
        service: "Free cancellation",
        pay: "No prepayment needed - pay at the property",
        roomleft: "Only 3 rooms left at this price on our site",
        btn: "",
        rate: "Wonderful",
        review : "203 reviews",
        no: "9.1",
        loc: "",
        people: "2 nights, 2 adults",
        rupee: "₹ 2,047",
        tax: "+₹ 245 taxes and fees",
        see: " See availability >"
    },
    {
        id: "8",
        image: "/images/cp8.webp",
        name: "Hotel De Glance - A Corporate Hotel near to Railway Station Udaipur",
        subname: "Udaipur",
        map: "show on map",
        town: "1.5 km from downtown",
        room: "Double Room",
        bed: "1 full bed",
        service: "Free cancellation",
        pay: "No prepayment needed - pay at the property",
        roomleft: "",
        btn: "New to Booking.com",
        rate: "Exceptional",
        review : "7 reviews",
        no: "10",
        loc: "Location 10",
        people: "2 nights, 2 adults",
        rupee: "₹ 2,820",
        tax: "+₹ 338 taxes and fees",
        see: " See availability >"
    },
    {
        id: "9",
        image: "/images/cp9.webp",
        name: "Fateh Niwas by Fateh Collection",
        subname: "Udaipur",
        map: "show on map",
        town: "4.3 km from downtown",
        room: " Double Room with Balcony",
        bed: "1 full bed",
        service: "breakfast included",
        pay: "",
        roomleft: "",
        btn: "",
        rate: "Excellent",
        review : "86 reviews",
        no: "8.8",
        loc: "",
        people: "2 nights, 2 adults",
        rupee: "₹ 9,524",
        tax: "+₹ 1,143 taxes and fees",
        see: " See availability >"
    },
    {
        id: "10",
        image: "/images/cp10.webp",
        name: "Vallabhgarh A lake facing balcony",
        subname: "Udaipur",
        map: "show on map",
        town: "2.1 km from downtown",
        room: "Deluxe Double Room",
        bed: "1 full bed",
        service: "Free cancellation",
        pay: "No prepayment needed - pay at the property",
        roomleft: "Only 4 rooms left at this price on our site",
        btn: "",
        rate: "Excellent",
        review : "58 reviews",
        no: "8.8",
        loc: "",
        people: "2 nights, 2 adults",
        rupee: "₹ 2,352",
        tax: "+₹ 282 taxes and fees",
        see: " See availability >"
    }

];